# use the Travis Container-Based Infrastructure
sudo: false

language: android
jdk: oraclejdk8

cache: false
dist: trusty

env:
  global:
    - EMULATOR_API=16
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_TRAVIS=1
    - secure: iXVs65+lPjyTr60MsX9K2WpjJ5ijt4cnBE9PT6ouHSjkZjugotaNoX3nXZev8fKFLsH0JPxpsxBVy66jz6iOddMfLdzSiL2oOeeYNxyNThOdGp9R/JmYtivgrMm6v3e1zzCLvj9onOwBUVdWVLD/BXgYi7wP96rJFENlVjuszys=
    - secure: BXwZhWDFFXzdaTAPAvMKeOfnLHxkmdXoeMZ/GtVYkT62JxeuiaTW6Z6rT0gZKAEyxmUBxFX1CP+1m1Gi0cWrQHfTBbFDJO7iKu7mG9LcZhQ8Cm657yt2TBc+fnVqbG5OxXWhSBs1lF1gZJ6+ehEIJn3YjP6fDYv0fNnTGpYHCYo=

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS

licenses:
  - android-sdk-license-.+
  - '.+'

before_install: echo 'count=0' > /home/travis/.android/repositories.cfg

install:
  - yes | sdkmanager "tools"

before_script:
  - export PATH="$ANDROID_HOME/emulator:$PATH"
  - sdkmanager "system-images;android-"$EMULATOR_API";default;armeabi-v7a"
  - echo no | avdmanager -v create avd -f -n test -k "system-images;android-"$EMULATOR_API";default;armeabi-v7a"
  - avdmanager list
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  # travis builds timeout after 10 min of not seeing any output, hence the below work-around
  # default travis_wait method doesn't show output until command finishes while this way allows us to see it
  - (while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &)
  - ./gradlew createDebugCoverageReport coveralls

deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
